### ISSUE TITLE
org.json.JSONException: JSON does not allow non-finite numbers.

### ISSUE THREAD

**Issue by mmahacek** [OpenNMS/opennms-brannock#1]
The following error was generated in kafka.log when trying to run on a 28.0.2 install on Ubuntu.
```
2021-08-18T16:05:00,469 | INFO  | fileinstall-/usr/share/opennms/deploy | fileinstall                      | 12 - org.apache.felix.fileinstall - 3.6.8 | Installing bundle org.opennms.tools.brannock / 1.0.0
2021-08-18T16:05:00,514 | WARN  | fileinstall-/usr/share/opennms/deploy | fileinstall                      | 12 - org.apache.felix.fileinstall - 3.6.8 | Error while starting bundle: file:/usr/share/opennms/deploy/brannock-1.0.jar
org.osgi.framework.BundleException: Activator start error in bundle org.opennms.tools.brannock [424].
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2290) ~[?:?]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2146) ~[?:?]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998) ~[?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [!/:3.6.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [!/:3.6.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) [!/:3.6.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [!/:3.6.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [!/:3.6.8]
Caused by: org.json.JSONException: JSON does not allow non-finite numbers.
	at org.json.JSONObject.testValidity(JSONObject.java:2009) ~[json-20171018.jar:?]
	at org.json.JSONObject.put(JSONObject.java:1610) ~[json-20171018.jar:?]
	at org.opennms.netmgt.brannock.Brannock.addJmxAttribute(Brannock.java:178) ~[?:?]
	at org.opennms.netmgt.brannock.Brannock.doJmxAttributes(Brannock.java:102) ~[?:?]
	at org.opennms.netmgt.brannock.Brannock.start(Brannock.java:83) ~[?:?]
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697) ~[?:?]
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240) ~[?:?]
	... 7 more
```

**Comment by jeffgdotorg** [comment]
Fixed in 3998758. Thanks for the report!
